### ISSUE TITLE
Final Capstone group project: set up your Kanban board

### ISSUE THREAD

**Issue by Benmuiruri** [Prestine-Cars/prestine-cars-backend#11]
Our Project has four people in it. 

1. Team member **One** [Ben Kiarie](https://github.com/Benmuiruri)
2. Team member **Two** [Sirri Ryisa](https://github.com/SirriRyisa)
3. Team member **Three** [Selma Belhadj](https://github.com/selma-belhadj)
4. Team member **Four** [Christian Munezero](https://github.com/kaitcham)

The link to our Kanban Board is https://github.com/orgs/Prestine-Cars/projects/1/views/1

Link to our [Front end project](https://github.com/Prestine-Cars/prestine-cars-frontend)
Link to our [Back end project](https://github.com/Prestine-Cars/prestine-cars-backend)

![project_start](https://user-images.githubusercontent.com/2597305/184606103-752a2ca4-2b24-4c79-a380-852b9a3fe586.png)

**Comment by MuriloRoque** [comment]
Hi @Benmuiruri, @selma-belhadj, @kaitcham, @SirriRyisa,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
